name: Run Release Please on push to main
run-name: ${{ github.actor }} has pushed to main, kicking off Release Please 🤖
on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      # Generated token lives for a hour, and it will get automatically revoked after job finishes
      # The token is masked, it cannot be logged accidentally.
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          token: ${{ steps.app-token.outputs.token }}
          release-type: "python"
